FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

LABEL maintainer="thomst08"

# Install node
RUN apt-get update
RUN apt-get install -y \
    nodejs \
    npm

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN npm install --prefix ClientApp
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /root/
COPY --from=build-env /app/out .
COPY --from=build-env /app/out/ClientApp ./ClientApp

RUN mkdir -p /root/config

ENV ASPNETCORE_URLS=http://+:4545
EXPOSE 4545

ENTRYPOINT ["dotnet", "Askarr.WebApi.dll"]
